### ISSUE TITLE
Query regarding downstream task

### ISSUE THREAD

**Issue by sauradip** [thunlp/PEVL#2]
Hi AUthors,

Thanks for making code available for this awesome work. My question is like Pix2seq did for object detection , can this work can be applied to dense prediction task like : Semantic Segmentation etc ?

**Comment by qyc-98** [comment]
Hi, intuitively, it is possible to apply PEVL to semantic segmentation. You can refer to this [paper](https://arxiv.org/abs/2105.05633)， basically, you just need to replace 'tree', 'sidewalk', 'person' with your query text label.
