### ISSUE TITLE
Code for ALBEF's VCR

### ISSUE THREAD

**Issue by vateye** [thunlp/PEVL#5]
Hi, can you share the codebase of finetuning for VCR task with pure ALBEF model? Thanks.

**Comment by qyc-98** [comment]
Hi,

It'll be released in two weeks!

Best

**Comment by vateye** [comment]
Hi, Any update? 👍

**Comment by vateye** [comment]
Thanks for the update for VCR code. But did you have some instruction on how to training the pure ALBEF for VCR task?

**Comment by qyc-98** [comment]
Hi, yes, I will update it today.

**Comment by vateye** [comment]
Thanks for your reply. Looking forward to seeing the pure VCR for ALBEF since I would like to conduct experiment based on this.
