### ISSUE TITLE
train for vcr

### ISSUE THREAD

**Issue by F-Yuan303** [thunlp/PEVL#7]
Hi, i cannot find these files in this repo:
train_vcr_file: ['./2022_01_06_vcr_pretrain_prompt_data.json'] 
train_val_vcr_q2a_file: ['./pevl_vcr_itm_finetune_val_QA_data.json']
train_val_vcr_qa2r_file: ['./pevl_vcr_itm_finetune_val_QAR_data.json']

and could you offer the command to train vcr task

**Comment by qyc-98** [comment]
sorry for my late reply！I will upload it today.
